# Dependabot configuration file
# <https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file>
#
# Each ecosystem is checked on a scheduled interval defined below.  To trigger
# a check manually, go to
#
#   https://github.com/nextstrain/ncov/network/updates
#
# and look for a "Check for updates" button.  You may need to click around a
# bit first.
---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
