# This analysis-specific config file overrides the settings in the default config file.
# If a parameter is not defined here, it will fall back to the default value.


configfile:
  - default_config/default_config.yaml # Pull in the default values
  - my_analyses/example/builds.yaml # Pull in our list of desired builds

config:
  - sequences=input_data/example_sequences.fasta
  - metadata=input_data/example_metadata.tsv

# Set the maximum number of cores you want Snakemake to use for this pipeline.
cores: 2

# Always print the commands that will be run to the screen for debugging.
printshellcmds: True

# Print the reason why each rule is running.
# This can help you understand why Snakemake is trying to re-run something you didn't expect it to.
reason: True
