name: preprocess-gisaid

on:
  ## This workflow is intended to be run via a repository dispatch event sent from
  ## https://github.com/nextstrain/ncov-ingest/blob/master/.github/workflows/fetch-and-ingest-gisaid-master.yml
  repository_dispatch:
    types:
      - preprocess-gisaid
  ## Manual running (via GitHub UI) is also be available, if needed, via workflow dispatch
  workflow_dispatch:
    inputs:
      trial_name:
        description: 'Short name to use as a prefix for the uploaded data. WARNING: without this we will overwrite the files in s3://nextstrain-ncov-private.'
        required: false

env:
  S3_DST_BUCKET: ${{ github.event.inputs.trial_name && format('nextstrain-ncov-private/trial/{0}', github.event.inputs.trial_name) || 'nextstrain-ncov-private' }}


jobs:
  gisaid:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Setup
      run: ./scripts/setup-github-workflow

    - name: Launch preprocess build
      run: |
        set -x
        nextstrain build \
          --aws-batch \
          --cpus 16 \
          --detach \
          --memory 31GiB \
            . \
            upload \
            ${{ github.event.inputs.trial_name=='' && 'trigger_phylogenetic_rebuild' || '' }} \
            --set-threads align=16 \
            --profile nextstrain_profiles/nextstrain-gisaid-preprocess \
            --config \
              S3_DST_BUCKET=${S3_DST_BUCKET} \
              ${{ github.event.inputs.trial_name=='' && format('slack_token={0}', env.SLACK_TOKEN) || '' }} \
              github_token=${PAT_GITHUB_DISPATCH} \
        |& tee build-launch.log
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        PAT_GITHUB_DISPATCH: ${{ secrets.PAT_GITHUB_DISPATCH }}

    - name: Build info
      run: |
        echo "--> Preprocessed files will be uploaded as:"
        echo "    s3://${S3_DST_BUCKET}/aligned.fasta.xz"
        echo "    s3://${S3_DST_BUCKET}/filtered.fasta.xz"
        echo "    s3://${S3_DST_BUCKET}/mutation-summary.tsv.xz"
        echo
        echo "--> Attach command"
        tail -n1 build-launch.log
        echo
        JOBID=$( tail -n1 build-launch.log | sed -E 's/.+attach ([-a-f0-9]+).+/\1/' )
        echo "--> View this job in the AWS console via"
        echo "    https://console.aws.amazon.com/batch/home?region=us-east-1#jobs/detail/${JOBID}"
        echo
        echo ${{ github.event.inputs.trial_name=='' && '--> When this job completes, a phylogenetic rebuild will be triggered' || '--> This is a trial build, and as such won\''t trigger a phylogenetic rebuild' }}
